sudo: false
language: node_js
node_js:
- stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower grunt-cli
- npm install
- bower install
script: grunt
deploy:
  provider: npm
  email: m.r992@hotmail.com
  api_key:
    secure: j0XVhCsca6ys908kJSofSe6/pi3udBLzSpppg4tI3sVdQlkoUpknY1oHIFFzwlcPqsqPHte5TFRFl/Ma4jdTRMsb1O/M+l69I7olvYaybGFzKrkhQpjL5FvsVQ3SbVLnsIPW4tV4CLIcCYllBOHXVkMacn2Drv0szjsNVDu69BP8KqhSTjs7j/RIR3UasBcSFRyFJTuwdmzIbedFugGwnPpSLFP1vE1veGIdFQXGlYMmGsZk8Bif+LyjTWawmhBdGyl04j6dW05ab+KzE7nnAryAVSLwBW/nNAIdiC3URBUWXcAKBwjzHJnxet6VAXRYfA5VrMHgrlpbaRBSKoS06Gon9olG7rv2BEFezriBR2yjepV3kzs94UB0tfBvEqVTDoRdwTGjxpzLWJcP0caoffG8mzmuMlXhDRUvY/99YxFmM+O+9C0FcXU4nxe1pIx0YqD64lZEOFiHEhhEuJqNKUaklIh9AuJ7H+GwEtVKUKlv3AcQB53aIay0enX196yL6q4TRyu8t3wmCjwgnzJ/IyMNoPf0fcqbaLrhq2ZwGIhoJkAZ0IgjE8jice+8jnGc+1vpVEpUsNV69CXogkQP3CL3FkeswWwFyiZmXDILaSshUfZqFu+xU1tbL9NCUZfajZj2TO1J5ZRfzBaBYRAI25+GRpOAflTHismAF8ENsMw=
  on:
    tags: true
notifications:
  email: false
